### ISSUE TITLE
Error on show cards

### ISSUE THREAD

**Issue by bostjan-cigan** [resultdoo/planning-poker#2]
Sometimes an error is triggered when showing cards. Must investigate.

`2020-11-16T23:24:06.341256134Z Uncaught excception Error: null value found for non-nullable type: Boolean!: {"response":{"errors":[{"extensions":{"path":"$.variableValues.showCards","code":"validation-failed"},"message":"null value found for non-nullable type: Boolean!"}],"status":200},"request":{"query":"\n\t\t\tmutation updateCards( $roomCode: String!, $showCards: Boolean! ) {\n\t\t\t\tupdate_scrum_cards(_set: { show: $showCards }, where: { room: { room_code: { _eq: $roomCode } } } ) {\n\t\t\t\t\taffected_rows\n\t\t\t\t}\t\n\t\t\t}\n\t\t","variables":{"roomCode":"KHZU","showCards":null}}}
2020-11-16T23:24:06.341309636Z at GraphQLClient.<anonymous> (/usr/src/app/node_modules/graphql-request/dist/src/index.js:116:35)
2020-11-16T23:24:06.341323502Z at step (/usr/src/app/node_modules/graphql-request/dist/src/index.js:40:23)
2020-11-16T23:24:06.341334278Z at Object.next (/usr/src/app/node_modules/graphql-request/dist/src/index.js:21:53)
2020-11-16T23:24:06.341367227Z at fulfilled (/usr/src/app/node_modules/graphql-request/dist/src/index.js:12:58)
2020-11-16T23:24:06.341375296Z at runMicrotasks (<anonymous>)
2020-11-16T23:24:06.341399329Z at processTicksAndRejections (internal/process/task_queues.js:93:5) {
2020-11-16T23:24:06.341407065Z response: { errors: [ [Object] ], status: 200 },
2020-11-16T23:24:06.341413791Z request: {
2020-11-16T23:24:06.341423072Z query: '\n' +
2020-11-16T23:24:06.341429864Z '\t\t\tmutation updateCards( $roomCode: String!, $showCards: Boolean! ) {\n' +
2020-11-16T23:24:06.341437255Z '\t\t\t\tupdate_scrum_cards(_set: { show: $showCards }, where: { room: { room_code: { _eq: $roomCode } } } ) {\n' +
2020-11-16T23:24:06.341444562Z '\t\t\t\t\taffected_rows\n' +
2020-11-16T23:24:06.341451382Z '\t\t\t\t}\t\n' +
2020-11-16T23:24:06.341458284Z '\t\t\t}\n' +
2020-11-16T23:24:06.341464930Z '\t\t',
2020-11-16T23:24:06.341471732Z variables: { roomCode: 'KHZU', showCards: null }
2020-11-16T23:24:06.341478462Z }
2020-11-16T23:24:06.341484706Z }`

**Comment by bostjan-cigan** [comment]
Issue is resolved.
